export type Source = { id: string; title: string; url: string };

export const SOURCES: Record<string, Source> = {
  S1:  { id: "S1",  title: "ambulante dienste e.V. – Startseite",                          url: "https://www.adberlin.com/neu/" },
  S2:  { id: "S2",  title: "Der Verein ambulante dienste e. V.",                            url: "https://www.adberlin.com/neu/der-verein-ambulante-dienste-e-v" },
  S3:  { id: "S3",  title: "Impressum ambulante dienste e.V.",                              url: "https://www.adberlin.com/neu/impressum" },
  S4:  { id: "S4",  title: "Die Einsatzstelle in Berlin-Schöneberg",                        url: "https://www.adberlin.com/neu/assistenzdienst/einsatzstelle" },
  S5:  { id: "S5",  title: "Unsere Beratungsbüros",                                         url: "https://www.adberlin.com/neu/assistenzdienst/beratungsbueros" },
  S6:  { id: "S6",  title: "Qualitätsmanagement – Startseite",                              url: "https://www.adberlin.com/neu/assistenzdienst/qualitatsmanagement-startseite" },
  S7:  { id: "S7",  title: "Leitbild (Handlungsgrundlagen, PDF)",                           url: "http://www.adberlin.com/downloads/Leitbild_Handlungsgrundlagen.pdf" },
  S8:  { id: "S8",  title: "Leitbild (umfassende Positionen, PDF)",                         url: "http://www.adberlin.com/downloads/Leitbild_umfassende%20Positionen.pdf" },
  S9:  { id: "S9",  title: "40 Jahre ambulante dienste e.V. (PDF)",                         url: "http://www.adberlin.com/downloads/2021-05-10%20_%2040%20Jahre%20ambulante%20Dienste%20_%20Endfassung.pdf" },
  S10: { id: "S10", title: "Flyer Persönliche Assistenz (PDF)",                             url: "http://www.adberlin.com/downloads/Flyer_persoenliche-Assistenz_web.pdf" },
  S11: { id: "S11", title: "Flyer Persönliches Budget (PDF)",                               url: "http://www.adberlin.com/downloads/Flyer_persoenliches-Budget_web.pdf" },
  S12: { id: "S12", title: "Betriebsrat ambulante dienste e.V.",                            url: "https://betriebsrat-ad.de/" },
  S13: { id: "S13", title: "Betriebsrat – Archiv (site36.net)",                             url: "https://betriebsrat-ad.site36.net/" },
  S14: { id: "S14", title: "Ver.di & friends (BR-Liste)",                                   url: "https://verdiandfriends.de/" },
  S15: { id: "S15", title: "Tarifkampagne ad + NLW",                                        url: "https://verdi-ad-lw.de/" },
  S16: { id: "S16", title: "Haustarifvertrag ambulante dienste e.V.",                       url: "https://verdi-ad-lw.de/haustarifvertrag-ambulante-dienste-e-v/" },
  S17: { id: "S17", title: "Haustarifvertrag Neue Lebenswege GmbH",                         url: "https://verdi-ad-lw.de/haustarifvertrag-neue-lebenswege/" },
  S18: { id: "S18", title: "Hilfelotse Berlin – Einsatzstelle-Eintrag",                     url: "https://www.hilfelotse-berlin.de/detail/ambulante-dienste-e-v-einsatzstelle" },
  S19: { id: "S19", title: "TopQM Berlin – Einrichtungsstammdaten",                         url: "https://soziale-dienste.berlin.de/topqm-prod/topqw-web/Stammdaten.aspx?EIID=b846593d-e5c5-40be-9623-342c66c722e9" },
  S20: { id: "S20", title: "Paritätischer Berlin – Mitgliederliste",                        url: "https://www.paritaet-berlin.de/mitglieder/unsere-mitgliedsorganisationen" },
  S21: { id: "S21", title: "Wichtige Kontaktdaten (Mitarbeiter*innen)",                     url: "https://www.adberlin.com/neu/mitarbeiterinnenbereich_startseite/wichtige-telefonnummern" },
  S22: { id: "S22", title: "LinkedIn ambulante dienste e.V.",                               url: "https://de.linkedin.com/company/ad-berlin" },
  S23: { id: "S23", title: "Kontaktseite ambulante dienste e.V.",                           url: "https://www.adberlin.com/neu/kontakt" },
  S24: { id: "S24", title: "Betriebsrat ad: Haustarifvertrag (Dossier)",                    url: "https://betriebsrat-ad.de/haustarifvertrag/" },
  S25: { id: "S25", title: "Hilfelotse Berlin – Beratungsbüro Süd",                         url: "https://www.hilfelotse-berlin.de/detail/ambulante-dienste-e-v-beratungsbuero-sued" },
  S26: { id: "S26", title: "Stellenangebote ambulante dienste e.V.",                        url: "https://www.adberlin.com/neu/stellen" },
  S27: { id: "S27", title: "Qualifizierung von Assistent*innen",                            url: "http://www.adberlin.com/neu/unser-angebot/qualifizierung-von-assistentinnen" },
  S28: { id: "S28", title: "Urlaubs- / Reiseassistenz",                                     url: "http://www.adberlin.com/neu/unser-angebot/personliche-assistenz/personliche-assistenz-in-besonderen-lebenssituationen/urlaubs-bzw-reiseassistenz" },
  S29: { id: "S29", title: "Persönliche Assistenz – Leistungsbeschreibung",                 url: "https://www.adberlin.com/neu/unser-angebot/personliche-assistenz" },
  S30: { id: "S30", title: "Berliner Rahmenvertrag § 131 SGB IX (PDF)",                     url: "https://umsetzungsbegleitung-bthg.de/w/files/umsetzungsstand/2019-06-05_landesrahmenvertrag-berlin.pdf" },
  S31: { id: "S31", title: "Eingliederungshilfe beantragen – Service Berlin",               url: "https://service.berlin.de/dienstleistung/324484/" },
  S32: { id: "S32", title: "Betriebsrat ad (Archiv): HTV-Dossier",                          url: "https://betriebsrat-ad.site36.net/dossiers/haustarifvertrag/" },
  S33: { id: "S33", title: "Dienstleistungen für Persönliches Budget",                      url: "https://www.adberlin.com/neu/unser-angebot/dienstleistungen-fur-bezieherinnen-eines-personlichen-budgets" },
  S34: { id: "S34", title: "Senatsverwaltung Integration, Arbeit, Soziales – Sozialrecht",  url: "https://www.berlin.de/sen/soziales/" },
  S35: { id: "S35", title: "Umsetzungsbegleitung BTHG – EGH vs. Pflege",                    url: "https://umsetzungsbegleitung-bthg.de/bthg-kompass/bk-schnittstellen/eingliederungshilfe-gesetzliche-pflegeversicherung-hilfe-zur-pflege/" },
  S36: { id: "S36", title: "Das Örtliche – Beratungsbüro Süd (Gneisenaustr.)",              url: "https://www.dasoertliche.de/Themen/Ambulante-Dienste-e-V-Beratungsb%C3%BCro-S%C3%BCd-Berlin-Kreuzberg-Gneisenaustr" },
};
